#version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db_data/dvdrental.tar:/tmp/dvdrental.tar

  app:
    build: .
    container_name: sql-agent-app
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - sql_agent_data:/app/data
    env_file:
      - .env
    stdin_open: true
    tty: true  

volumes:
  pgdata:
  sql_agent_data:
